# Generated by Django 3.0.3 on 2020-02-17 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200212_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 17, 19, 42, 32, 277786, tzinfo=utc)),
        ),
    ]
