# Generated by Django 3.0.3 on 2020-02-20 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200217_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 20, 20, 53, 53, 830404, tzinfo=utc)),
        ),
    ]
