# Generated by Django 3.0.3 on 2020-02-24 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200220_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 24, 20, 36, 52, 856974, tzinfo=utc)),
        ),
    ]
