# Generated by Django 3.0.3 on 2020-02-24 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200224_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 24, 20, 46, 25, 907203, tzinfo=utc)),
        ),
    ]
